# Blog info
blog_name: Geepair
slogan: Study hard, study forever
url: https://beet.tk

# Set avatar (Absolute url and relative url)
avatar: https://cdn.jsdelivr.net/gh/geepair/blog@latest/themes/fexo/source/images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: geepair,java,java开发,后端开发,spring,springboot

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/geepair
    target_blank: true
  - name: Cnblogs
    url: https://www.cnblogs.com/geepair
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: Go

search_slogan:
  isShow: true # true|fase
  text: Some thing you want to study ~

link_slogan:
  isShow: true # true|fase
  text: Send mail to - geepair@163.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持Geepair
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: false

rss: /atom.xml

sitemap: /sitemap.xml

baidu_verification: code-4lxY7hVACI
  
# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
#google_analytics: UA-38189205-1
baidu_analytics: fed321f287cd87ac70e439a3009fb382

# Comment service

#disqus_shortname: forsigner
#hypercomments_id: 89821
#gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: false # 如果使用 gitalk，请设置改之为true
  clientID: 277317290454635afa73
  clientSecret: 78223c859304da5e8d71bfce136d436c6ff95c37
  repo: blog-comment
  owner: forsigner
  admin: forsigner


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: ture # 如果使用valine，请设置改之为true
  appid: qU4YrLrfbzb8Ycg4xF98RunS-gzGzoHsz # your leancloud application appid
  appkey: A5UPPRa1furzzUTg0WUJiw90 # your leancloud application appkey
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go ... # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "xxx"
    - "xxx"
    - "xxx"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@geepair"
    text_value_url: https://github.com/geepair
  - type: mail
    icon: icon-mail
    text_key: NeteaseMail
    text_value: "geepair@163.com"
    text_value_url: "mailto:geepair@163.com"
  - type: location
    icon: icon-location
    text_value: JiangXi

link:
  - name: Turingzz
    info: 一个混子…
    url: https://www.hanjun.red
    avatar: https://www.hanjun.red/image/avatar.jpeg

project:
  - type: personal
    name: animatecss-use
    url: https://github.com/geepair/animatecss-use
    intro: some animate css demo
